# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = false
snowballTrailDensity = 0.2
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = false
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "OFF"
endCrystalParticles = true
minecartLandingSparks = true
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true

[attacked]
chickenFeathers = false
parrotFeathers = false
snowGolemSnowflakes = false

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 1.0
playersHaveSleepingZs = true
villagerSnoreChance = 0.19607843137254902
villagerSnoreSoundVolume = 1.0
villagersHaveSleepingZs = true
foxesHaveSleepingZs = false
batsHaveSleepingZs = false
catsHaveSleepingZs = false
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = false

[humanoids]
drowningBubbles = "DEFAULT"
drowningBubblesDensity = 10

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
heartBeatingThreshold = 6
heartbeatVolume = 1.0

[dustClouds]
scale = 0.5
alpha = 0.3
playerFell = false
playerRunning = false
mobFell = false
mobRunning = false
landMaceAttack = true
preventWhenRaining = false

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true

[itemRarity]
particlesDisplayType = "OFF"
particleColor = "NAME_COLOR"
mixedColorName = true
particleMaxHeight = 7

[primedTNT]
updateSmoke = true
flames = true
sparks = true