# Use Cloth Config mod for the descriptions.
---
snowGravity: false
snowMakingIce: true
snowAlwaysReplaceable: true
thinnerBoundingBox: true
snowNeverMelt: false
snowReduceFallDamage: true
sustainGrassIfLayerMoreThanOne: true
sneakSnowball: false
fancySnowOnUpperSlab: true
mobSpawningMaxLayers: 8
snow-cover:
  replaceWorldgenFeature: true
  placeSnowOnBlock: true
  retainOriginalBlocks: false
  placeNaturally: true
accumulation:
  naturalMelting: true
  snowAndIceMeltInWarmBiomes: false
  maxLayers: 2
  accumulatesDuringSnowstorm: true
  accumulatesDuringSnowfall: false
debug:
  weatherTickSlowness: 16
  mobSpawningCommand: false
