!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 4
allowAdventureTwerking: false
chance: 0.1
debug: false
enableAE2Accelerator: false
enableDirtToGrass: false
enableMysticalCrops: false
hoeTakesDamage: false
ignoreList: ['#minecraft:saplings']
randomTickMultiplier: 1
range: 2
requireHoe: false
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: []
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 2
useWhitelist: true
